Bugfix/save state
Taanviir/ft_transcendence pull request #56
Opened 2024-10-18 16:35 UTC by tehuanmelo

2024-10-18 21:09 UTC, Taanviir requested changes
I have looked at the code and tested the changes however there was an issue where any link other than `localhost` threw a 404 error if entered in the URL search bar.

2024-10-18 21:09 UTC, Taanviir commented on backend/static/scripts/main.js
> +    document.title = '';
also why is this being done

2024-10-20 08:10 UTC, tehuanmelo commented on backend/static/scripts/main.js
> +    document.title = '';
it must be there, to prevent caching

2024-10-20 08:19 UTC, tehuanmelo commented
> I have looked at the code and tested the changes however there was an issue where any link other than `localhost` threw a 404 error if entered in the URL search bar.

Issue fixed.
Please review it and let me know if the error persists.

2024-10-20 08:23 UTC, Taanviir approved these changes
Everything looks good, you can go ahead and merge

2024-10-20 10:37 UTC, merged